name: CI/CD Pipeline
on:
  push:
    branches: [main, develop]

env:
  AWS_REGION: ap-south-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}
      environment: ${{ steps.meta.outputs.env }}
    steps:
      - uses: actions/checkout@v4

      - name: Set metadata
        id: meta
        run: |
          TAG="${GITHUB_SHA::8}"
          ENV=$([ "$GITHUB_REF_NAME" = "main" ] && echo "prod" || echo "dev")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "env=$ENV" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        working-directory: ./app
        run: |
          ENV=${{ steps.meta.outputs.env }}
          TAG=${{ steps.meta.outputs.tag }}
          IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gitops-platform/${ENV}/myapp:${TAG}"
          docker build -t $IMAGE .
          docker push $IMAGE

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag
        run: |
          ENV=${{ needs.build-and-push.outputs.environment }}
          TAG=${{ needs.build-and-push.outputs.image-tag }}
          sed -i "s/tag: .*/tag: ${TAG}/" helm/myapp/values-${ENV}.yaml
          git config user.email "ci@gitops"
          git config user.name "CI Bot"
          git add .
          git commit -m "deploy: ${ENV} → ${TAG}"
          git push
